from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student/<slug:stud_id>/attendance/',
         views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/',
         views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/',
         views.timetable, name='timetable'),
    path('profile/', views.profile, name='profile'),
    path('directory/', views.directory, name='directory'),

    path('student/<slug:stud_id>/marks_list/',
         views.marks_list, name='marks_list'),

    path('teacher/<slug:teacher_id>/<int:choice>/Classes/',
         views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/',
         views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/',
         views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/',
         views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/',
         views.t_attendance, name='t_attendance'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/',
         views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/',
         views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/',
         views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Extra_class/',
         views.t_extra_class, name='t_extra_class'),
    path('teacher/<slug:assign_id>/Extra_class/confirm/',
         views.e_confirm, name='e_confirm'),
    path('fees/add-class/', views.add_class_fee, name='add_class_fee'),
    path('fees/receipt/<int:transaction_id>/', views.fee_receipt,
         name='fee_receipt'),
    path('student/<str:stud_id>/marks_card/', views.marks_card,
         name='marks_card'),
    path('teacher/<int:marks_c_id>/publish_marks/', views.publish_marks,
         name='publish_marks'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report'),
    path('teacher/<int:assign_id>/Report/export/', views.t_report_export,
         name='t_report_export'),

    path('teacher/<slug:teacher_id>/t_timetable/',
         views.t_timetable, name='t_timetable'),
    path('teacher/<int:asst_id>/Free_teachers/',
         views.free_teachers, name='free_teachers'),

    path('teacher/<int:assign_id>/marks_list/',
         views.t_marks_list, name='t_marks_list'),
    path('teacher/<int:assign_id>/Students/Marks/',
         views.student_marks, name='t_student_marks'),
    path('teacher/<int:marks_c_id>/marks_entry/',
         views.t_marks_entry, name='t_marks_entry'),
    path('teacher/<int:marks_c_id>/marks_entry/confirm/',
         views.marks_confirm, name='marks_confirm'),
    path('teacher/<int:marks_c_id>/Edit_marks/',
         views.edit_marks, name='edit_marks'),
    path('api/auth/', include('djoser.urls')),
    path('add-teacher/', views.add_teacher, name='add_teacher'),
    path('add-student/', views.add_student, name='add_student'),

    path('student/<slug:stud_id>/fees/', views.fees, name='fees'),
    path('student/<slug:stud_id>/fees/export/', views.fees_export, name='fees_export'),
    path('fees/', views.t_fees, name='t_fees'),
    path('fees/add/', views.add_fee, name='add_fee'),
    path('fees/<int:fee_id>/edit/', views.edit_fee, name='edit_fee'),

    path('notices/', views.notices, name='notices'),
    path('notices/add/', views.add_notice, name='add_notice'),
    path('notices/<int:notice_id>/', views.notice_detail, name='notice_detail'),
    path('notices/<int:notice_id>/edit/', views.edit_notice, name='edit_notice'),
    path('notices/<int:notice_id>/delete/', views.delete_notice, name='delete_notice'),
]
admin.site.site_url = None
admin.site.site_header = 'My Site'
