# Generated by Django 4.2.16 on 2026-08-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0018_notice_fee"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assigntime",
            unique_together={("assign", "day", "period")},
        ),
    ]
