# Generated by Django 4.2.16 on 2026-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0021_seed_fee_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
