# Generated by Django 4.2.16 on 2026-08-15 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0022_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("attendance.marked", "Attendance marked"),
                            ("attendance.changed", "Attendance changed"),
                            ("attendance.cancelled", "Class cancelled"),
                            ("marks.entered", "Marks entered"),
                            ("marks.changed", "Marks changed"),
                            ("fee.payment", "Payment recorded"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("student_name", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="info.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="info_auditl_created_d8c8b2_idx"
                    ),
                    models.Index(
                        fields=["student", "-created_at"],
                        name="info_auditl_student_1473a3_idx",
                    ),
                ],
            },
        ),
    ]
