# Generated by Django 4.2.16 on 2026-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0023_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Login issue", "Cannot sign in"),
                            ("Password reset", "Forgotten password"),
                            ("Account locked", "Account locked"),
                            ("Wrong details", "My details are wrong"),
                            ("Other", "Something else"),
                        ],
                        default="Login issue",
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In progress", "In progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
