# Generated by Django 4.2.16 on 2026-08-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0024_supportrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="notice",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Exam", "Exam"),
                    ("Fee", "Fee"),
                    ("Event", "Event"),
                    ("Holiday", "Holiday"),
                    ("Administrative", "Administrative"),
                ],
                default="General",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="expires_at",
            field=models.DateField(
                blank=True, help_text="Hidden from students after this date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notice",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="message",
            field=models.TextField(max_length=5000),
        ),
        migrations.CreateModel(
            name="NoticeRead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="info.notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("notice", "user")},
            },
        ),
    ]
