# Generated by Django 4.2.16 on 2026-08-16 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0025_alter_notice_options_notice_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Credit weight used for SGPA/CGPA.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
