# Generated by Django 4.2.16 on 2026-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0026_course_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceclass",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Not taken"), (1, "Submitted"), (2, "Cancelled")],
                default=0,
            ),
        ),
    ]
