# Generated by Django 4.2.16 on 2026-08-16 08:29

from django.db import migrations, models


def publish_already_entered(apps, schema_editor):
    """Anything already entered was already visible to students.

    Publication is a new gate. Without this, every existing batch would flip to
    unpublished on deploy and every student's marks page would empty out - a
    migration silently taking data away from the people it belongs to.
    """
    MarksClass = apps.get_model("info", "MarksClass")
    MarksClass.objects.filter(status=True).update(is_published=True)


def unpublish_all(apps, schema_editor):
    MarksClass = apps.get_model("info", "MarksClass")
    MarksClass.objects.update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0027_alter_attendanceclass_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks",
            name="is_absent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marksclass",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marksclass",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("attendance.marked", "Attendance marked"),
                    ("attendance.changed", "Attendance changed"),
                    ("attendance.cancelled", "Class cancelled"),
                    ("marks.entered", "Marks entered"),
                    ("marks.changed", "Marks changed"),
                    ("marks.published", "Marks published"),
                    ("marks.unpublished", "Marks withdrawn"),
                    ("fee.payment", "Payment recorded"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="marksclass",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_already_entered, unpublish_all),
    ]
