# Generated by Django 4.2.16 on 2026-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0028_marks_is_absent_marksclass_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
