# Generated by Django 4.2.16 on 2026-08-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0029_student_address_student_phone_teacher_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="marks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendanceclass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info.attendanceclass"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="DOB",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info.class"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="DOB",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info.dept"
            ),
        ),
    ]
