# Generated by Django 4.2.16 on 2026-08-18 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0031_null_backfilled_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Unticking this blocks sign-in and hides the person from the directory. It keeps their records.",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Unticking this blocks sign-in and hides the person from the directory. It keeps their records.",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
