# Generated by Django 4.2.16 on 2026-08-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0032_student_is_active_teacher_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("attendance.marked", "Attendance marked"),
                    ("attendance.changed", "Attendance changed"),
                    ("attendance.cancelled", "Class cancelled"),
                    ("marks.entered", "Marks entered"),
                    ("marks.changed", "Marks changed"),
                    ("marks.published", "Marks published"),
                    ("marks.unpublished", "Marks withdrawn"),
                    ("fee.payment", "Payment recorded"),
                    ("accounts.imported", "Accounts imported"),
                ],
                max_length=40,
            ),
        ),
    ]
