# Generated by Django 5.2.17 on 2026-08-18 11:56

import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0034_loginevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Square images work best.",
                null=True,
                upload_to=info.models._photo_path,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Square images work best.",
                null=True,
                upload_to=info.models._photo_path,
            ),
        ),
    ]
