# Generated by Django 5.2.17 on 2026-08-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0036_passwordresetotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fee", "Fee reminder"),
                            ("attendance", "Low attendance"),
                            ("marks", "Marks released"),
                            ("notice", "Notice published"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("subject", models.CharField(max_length=200)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "unique_together": {("user", "key")},
            },
        ),
    ]
