# Generated by Django 5.2.17 on 2026-08-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0037_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="sent_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
