# Generated by Django 5.2.17 on 2026-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0040_query_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_excused",
            field=models.BooleanField(default=False),
        ),
    ]
