# Generated by Django 5.2.17 on 2026-08-19 08:55

import django.db.models.deletion
import info.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0041_attendance_excused"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Medical", "Medical"),
                            (
                                "Official duty",
                                "Official duty (sport, event, placement)",
                            ),
                            ("Personal", "Personal"),
                        ],
                        default="Medical",
                        max_length=20,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("reason", models.TextField(max_length=1000)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF or image, up to 5 MB.",
                        null=True,
                        upload_to=info.models._leave_document_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Awaiting a decision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.TextField(blank=True, max_length=1000)),
                ("sessions_excused", models.PositiveIntegerField(default=0)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="info.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_date", "-created_at"],
            },
        ),
    ]
