# Generated by Django 5.2.17 on 2026-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0044_attendance_correction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fee", "Fee reminder"),
                    ("attendance", "Low attendance"),
                    ("marks", "Marks released"),
                    ("notice", "Notice published"),
                    ("query", "Mark query"),
                    ("leave", "Leave application"),
                    ("correction", "Attendance dispute"),
                ],
                max_length=20,
            ),
        ),
    ]
